### PR TITLE
Fix issue #35

### PR DESCRIPTION
**Pull request by oldgreen**
These changes fix the problem described under issue #35 (periodic disconnects when the client keeps frequently sending (only) QoS 0 messages). Please see the individual commit messages for details.

### CODE REVIEW

**Comment by p-goudet** [comment]
Thank you very much, I am checking at this approach to handle the ping message.

**Comment by arizz96** [comment]
Any news here?

**Comment by p-goudet** [comment]
@oldgreen Thank you again for your contribution. 
There was a small issue remaining. After a reconnection, the client would stop trying to ping the server, because the last_pingresp_receive_at value would not be updated. I also did some small refactoring. 
I have issued a new pull request based on your work:
[https://github.com/RubyDevInc/paho.mqtt.ruby/pull/47](https://github.com/RubyDevInc/paho.mqtt.ruby/pull/47)

Could you tell me if those modifications are fine for you?

**Comment by oldgreen** [comment]
@p-goudet yes, please feel free to do any modifications. Thanks.

**Comment by p-goudet** [comment]
This change have been add in the following mergre request.
[https://github.com/RubyDevInc/paho.mqtt.ruby/pull/47](https://github.com/RubyDevInc/paho.mqtt.ruby/pull/47)
Thank you for your contributions

**Pull request closed without merging**
