### PR TITLE
V 1.0.12

### PR DESCRIPTION
**Pull request by p-goudet**
The version 1.0.13 should fix the following issue:
- The nil error raised during re-initialization of publisher and subscriber
- The deadlock in the reading loop when frequency is too high

The encryption is now supporting keys generate using elliptical curve cryptography.

### CODE REVIEW

**Comment by rgaufman** [comment]
Looking forward to this release :P

**Comment by p-goudet** [comment]
@rgaufman I am glad to hear that, it should be release really soon.

@consulthys A simple solution has been add to handle error due to wrong key type. If the key is not RSA type, the client would attempt to read it as an EC keys. If both of them a then failed an exception would be raised. The method signature remain the same.

**Comment by consulthys** [comment]
Thanks a lot @p-goudet !!!

**Comment by consulthys** [comment]
@p-goudet Any ETA for releasing this on ruby gems?

**Pull request merged**
