### PR TITLE
35 fix periodic disc

### PR DESCRIPTION
**Pull request by p-goudet**
Fix the check alive process. The current version has a bug in handling of ping packet in case of sending qos = 0 package.

### CODE REVIEW

**Comment by rgaufman** [comment]
Any updates on this? :)

**Comment by p-goudet** [comment]
I am sorry I have been busy with other project lately. I would try to go back on this as soon as possible and finally merge it. 🙇

**Comment by rgaufman** [comment]
Any news? :P

**Comment by p-goudet** [comment]
I will to try to merge it by the end of this week. I have to review some local changes and check if I include them or not before that 🙇

**Comment by rgaufman** [comment]
Thank you, that would be great, will test as soon as it's released! :)

**Comment by rgaufman** [comment]
Thank you :) - is there an ETA for releasing paho-mqtt-1.0.13?

**Comment by p-goudet** [comment]
I don't know yet, very soon I hope :).

**Comment by rgaufman** [comment]
Thank you, looking forward :)

**Comment by rgaufman** [comment]
Friendly follow up :P

**Comment by rgaufman** [comment]
Any update? :)

**Comment by p-goudet** [comment]
This branch has been already merged on the master branch. Other change would be add to the master branch before the release of 1.0.13 version. You may download the source and install the gems by hand to get the latest update.

**Pull request merged**
